version: 2.1
orbs:
  python: circleci/python@1.5.0
  

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys: [env]
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            make install
      - run:
          name: Run tests
          command: |
            source env/bin/activate
            make lint
      - save_cache:
          paths: [./env]
          key: env


workflows:
  sample:
    jobs:
      - build-and-test
